#pragma once
#include "constants.h"

namespace Constants {

	int DIFFICULTY1_MAX_PLAYERS;
	int DIFFICULTY1_SIDE_SIZE;
	int DIFFICULTY1_NBFOOD;
	int DIFFICULTY1_NESTLINE;
	int DIFFICULTY1_NESTCOLUMN;
	int DIFFICULTY2_MAX_PLAYERS;
	int DIFFICULTY2_SIDE_SIZE;
	int DIFFICULTY2_NBFOOD;
	int DIFFICULTY2_NESTLINE;
	int DIFFICULTY2_NESTCOLUMN;
	int DIFFICULTY3_MAX_PLAYERS;
	int DIFFICULTY3_SIDE_SIZE;
	int DIFFICULTY3_NBFOOD;
	int DIFFICULTY3_NESTLINE;
	int DIFFICULTY3_NESTCOLUMN;

	float PHEROMON_DECREASE_AMOUNT;
	float PHEROMON_DROP_AMOUNT;

	bool VERBOSE;

	unsigned short SERVER_PORT;

}